#!/bin/sh
# put this file to /etc/init.d/
# chmod +x

PIDFILE=/var/run/parking.pid

case "${1}" in
	start)
		if [ -f ${PIDFILE} ]; then
			echo "Service already running with pid" `cat ${PIDFILE}`
			exit 0
		fi
		start-stop-daemon --start --background --pidfile ${PIDFILE} --make-pidfile --exec ${DAEMON}
        echo "Service started with pid" `cat ${PIDFILE}`
		;;
	stop)
		start-stop-daemon --stop --pidfile ${PIDFILE}
		rm ${PIDFILE}
        echo "Service stopped"
		;;
	restart)
		${0} stop
		${0} start
		;;
	status)
		if [ -f ${PIDFILE} ]; then
			echo "Service is running with pid" `cat ${PIDFILE}`
			exit 0
		fi
		echo "Service stopped"
		;;
	*)
		echo "Usage : ${0} {start|stop|restart|status}"
		exit 1
		;;
esac
